name: Laravel CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    # Paso 1: Clonar el repositorio
    - name: Checkout code
      uses: actions/checkout@v3

    # Paso 2: Configurar PHP y Composer
    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: 8.2
        extensions: mbstring, pdo, tokenizer, xml, bcmath

    - name: Install Composer dependencies
      run: composer install --no-progress --no-suggest --prefer-dist

    # Paso 3: Configurar entorno para pruebas
    - name: Create SQLite database
      run: |
        mkdir -p database
        touch database/database.sqlite

    - name: Set up environment
      run: |
        echo "APP_NAME=Laravel" > .env
        echo "APP_ENV=testing" >> .env
        echo "APP_KEY=" >> .env
        echo "APP_DEBUG=true" >> .env
        echo "APP_URL=http://localhost" >> .env
        echo "DB_CONNECTION=sqlite" >> .env
        echo "DB_DATABASE=./database/database.sqlite" >> .env
        echo "DB_FOREIGN_KEYS=true" >> .env

    - name: Generate application key
      run: php artisan key:generate

    # Paso 4: Crear migración adicional para agregar la columna `name`
    - name: Create migration to fix sectors table
      run: |
        php artisan make:migration add_name_to_sectores_table --table=sectores
        echo "<?php
        use Illuminate\\Database\\Migrations\\Migration;
        use Illuminate\\Database\\Schema\\Blueprint;
        use Illuminate\\Support\\Facades\\Schema;

        return new class extends Migration {
            public function up() {
                Schema::table('sectores', function (Blueprint \$table) {
                    \$table->string('name')->after('id');
                });
            }

            public function down() {
                Schema::table('sectores', function (Blueprint \$table) {
                    \$table->dropColumn('name');
                });
            }
        };" > database/migrations/$(ls -t database/migrations | head -n 1)

    # Paso 5: Ejecutar migraciones y seeders
    - name: Run database migrations and seed
      run: php artisan migrate --seed --force --env=testing

    # Paso 6: Instalar Node.js para assets front-end
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: Install front-end dependencies
      run: npm install

    - name: Build front-end assets
      run: npm run build

    - name: Verify Vite manifest
      run: |
        if [ ! -f public/build/manifest.json ]; then
          echo "Vite manifest not found!";
          exit 1;
        fi

    # Paso 7: Ejecutar pruebas
    - name: Run Laravel tests
      run: php artisan test

    # Paso 8: Empaquetar artefactos
    - name: Package application
      run: zip -r laravel-app.zip . -x "node_modules/*" "vendor/*"
      env:
        APP_ENV: production

    # Paso 9: Subir artefacto
    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: laravel-artifact
        path: laravel-app.zip

